name: colibri
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - black
  - jupyter
  - matplotlib
  - numpy
  - pandas
  - pytorch
  - python=3.11
  - pytz
  - requests
  - scikit-learn
  - seaborn
  - selenium
  - statsmodels
  - tabulate
  - time
  - tqdm
  - transformers
