name: colibri
channels:
  - defaults
  - conda-forge
  - anaconda
dependencies:
  - python=3.8
  - jupyter
  - pandas
  - selenium
  - requests
  - black
  - time
  - pytz
  - numpy
  - pytorch
  - transformers
  - scikit-learn
  - tqdm
  - matplotlib
  - seaborn
  - statsmodels